# -*- coding: utf-8 -*-
"""Data_Augmentation_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MohamedElSobkey/Data-Augmentation/blob/main/Data_Augmentation_.ipynb
"""

#Import libraries
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import array_to_img, img_to_array, load_img

datagen = ImageDataGenerator (
    rotation_range = 40,
		shear_range = 0.2,
		zoom_range = 0.2,
		horizontal_flip = True,
		brightness_range = (0.5, 1.5))
# Read image
img = load_img('Image.jpg')
# convert it to array
x = img_to_array(img)
# (300,500,3) to (1,300,500,3) 1 to be in array
x = x.reshape((1, ) + x.shape)
# batch_size = 1 for one image
i = 0
for batch in datagen.flow(x, batch_size = 1, save_to_dir =r'/content/prreview',
						save_prefix ='image', save_format ='jpeg'):
	i += 1
	if i > 5:
		break

import os
import matplotlib.pyplot as plt

for i in os.listdir('/content/prreview') :
  plt.imshow(plt.imread(os.path.join('/content/prreview',i)))
  plt.show()